const {
  BOT_TOKEN,
  BB2_ENDPOINT,
  BB2_ACCESS_KEY_ID,
  BB2_SECRET_ACCESS_KEY,
  BB2_BUCKET,
} = process.env;

module.exports = {
  BOT_TOKEN,
  BB2_ENDPOINT,
  BB2_ACCESS_KEY_ID,
  BB2_SECRET_ACCESS_KEY,
  BB2_BUCKET,
};
