import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://uainfo.pl">uainfo.pl</a>
        </h1>

        <p className={styles.description}>
          Aggregating information for helping people of Ukraine
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Section 1 &rarr;</h2>
            <p>Find in-depth information about section 1</p>
          </a>
          <a href="#" className={styles.card}>
            <h2>Section 1 &rarr;</h2>
            <p>Find in-depth information about section 1</p>
          </a>
          <a href="#" className={styles.card}>
            <h2>Section 1 &rarr;</h2>
            <p>Find in-depth information about section 1</p>
          </a>
          <a href="#" className={styles.card}>
            <h2>Section 1 &rarr;</h2>
            <p>Find in-depth information about section 1</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
